const translations = {
    es: {
        // ── Navigation ──────────────────────────────────────────────
        'nav.home': 'Inicio',
        'nav.news': 'Noticias',
        'nav.catalog': 'Catálogo',
        'nav.blog': 'Blog',
        'nav.agenda': 'Agenda',
        'nav.contact': 'Contacto',
        'nav.login': 'Acceder',
        'nav.dashboard': 'Dashboard',
        'nav.logout': 'Salir',

        // ── Page headers ─────────────────────────────────────────────
        'news.header.title': '📰 Centro de Noticias',
        'news.header.subtitle': 'Mantente al día con las últimas novedades del mundo gaming',
        'games.header.title': '🎮 Catálogo de Videojuegos',
        'games.header.subtitle': 'Los mejores juegos con valoraciones de prensa y comunidad',
        'games.sort.label': 'Ordenar por',
        'games.sort.press': 'Mejor calificación Prensa',
        'games.sort.community': 'Mejor calificación Comunidad',
        'games.sort.year': 'Más recientes',
        'games.sort.az': 'Nombre (A-Z)',
        'games.filter.genre': 'Género',
        'games.filter.platform': 'Plataforma',
        'games.genre.action': 'Acción',
        'games.genre.rpg': 'RPG',
        'games.genre.strategy': 'Estrategia',
        'games.genre.adventure': 'Aventura',
        'games.platform.pc': 'PC',
        'games.platform.console': 'Consolas',
        'games.platform.mobile': 'Mobile',
        'blog.header.title': '💭 Blog de Opinión',
        'blog.header.subtitle': 'Análisis y reflexiones de expertos sobre la industria gaming',
        'agenda.header.title': '📅 Agenda de Eventos',
        'agenda.header.subtitle': 'Lanzamientos, torneos y eventos del mundo gaming',
        'contact.header.title': '📬 Contacto',
        'contact.header.subtitle': 'Ponte en contacto con el equipo de Vortex Play',
        'footer.rights': '© 2026 Vortex Play. Todos los derechos reservados.',

        // ── Index ────────────────────────────────────────────────────
        'index.subtitle': 'Plataforma web de videojuegos: noticias, rankings y comunidad',
        'index.read_more': 'Leer más →',

        // ── News sidebar ─────────────────────────────────────────────
        'news.sidebar.categories': 'Categorías',
        'news.sidebar.trending': 'Tendencias',
        'news.sidebar.redaction': 'Redacción',
        'news.cat.all': '📊 Todas',
        'news.cat.tech': '🚀 Tecnología',
        'news.cat.esports': '🏆 Esports',
        'news.cat.launches': '🎮 Lanzamientos',
        'news.cat.trends': '📈 Tendencias',
        'news.cat.platforms': '☁️ Plataformas',
        'news.cat.streaming': '🎥 Streaming',
        'news.views': 'vistas',

        // ── Blog sidebar ─────────────────────────────────────────────
        'blog.sidebar.about_title': 'Sobre el Blog',
        'blog.sidebar.about_text': 'Espacio para análisis en profundidad, opiniones sin filtro y debate sobre videojuegos, tecnología y cultura gaming.',
        'blog.sidebar.authors': 'Autores',
        'blog.author1.role': 'Analista de eSports',
        'blog.author2.role': 'Tecnología y gráficos',

        // ── Comments ─────────────────────────────────────────────────
        'comment.section': 'Comentarios',
        'comment.empty': 'Sin comentarios todavía. ¡Sé el primero!',
        'comment.placeholder': 'Escribe un comentario...',
        'comment.as': 'Comentando como',
        'comment.submit': 'Publicar',
        'comment.reply': 'Responder',
        'comment.disabled': 'Los comentarios están desactivados temporalmente.',
        'comment.login_hint': 'Para comentar, <a href="auth.html">inicia sesión</a>.',
        'comment.login_react': 'Inicia sesión para reaccionar.',
        'comment.login_reply': 'Inicia sesión para responder.',
        'comment.min_chars': 'El comentario debe tener al menos 5 caracteres.',

        // ── Agenda ───────────────────────────────────────────────────
        'agenda.filter.all': 'Todos',
        'agenda.filter.launch': '🚀 Lanzamientos',
        'agenda.filter.tournament': '🏆 Torneos',
        'agenda.filter.update': '🔄 Actualizaciones',
        'agenda.filter.event': '🎪 Eventos',
        'agenda.weekday.mon': 'Lun',
        'agenda.weekday.tue': 'Mar',
        'agenda.weekday.wed': 'Mié',
        'agenda.weekday.thu': 'Jue',
        'agenda.weekday.fri': 'Vie',
        'agenda.weekday.sat': 'Sáb',
        'agenda.weekday.sun': 'Dom',
        'agenda.legend.launch': 'Lanzamiento',
        'agenda.legend.tournament': 'Torneo',
        'agenda.legend.update': 'Actualización',
        'agenda.legend.event': 'Evento',
        'agenda.empty': 'Selecciona un día para ver los eventos',
        'agenda.type.launch': 'Lanzamiento',
        'agenda.type.tournament': 'Torneo',
        'agenda.type.update': 'Actualización',
        'agenda.type.event': 'Evento',
        'agenda.month.0': 'Enero',
        'agenda.month.1': 'Febrero',
        'agenda.month.2': 'Marzo',
        'agenda.month.3': 'Abril',
        'agenda.month.4': 'Mayo',
        'agenda.month.5': 'Junio',
        'agenda.month.6': 'Julio',
        'agenda.month.7': 'Agosto',
        'agenda.month.8': 'Septiembre',
        'agenda.month.9': 'Octubre',
        'agenda.month.10': 'Noviembre',
        'agenda.month.11': 'Diciembre',

        // ── Roles ────────────────────────────────────────────────────
        'role.admin': 'Admin',
        'role.writer': 'Redactor',
        'role.collaborator': 'Colaborador',
        'role.subscriber': 'Suscriptor',
        'role.guest': 'Invitado',

        // ── Contact form ─────────────────────────────────────────────
        'contact.label.name': 'Nombre completo',
        'contact.label.email': 'Correo electrónico',
        'contact.label.subject': 'Asunto',
        'contact.label.message': 'Mensaje',
        'contact.placeholder.name': 'Tu nombre',
        'contact.placeholder.email': 'tu@email.com',
        'contact.placeholder.subject': '¿Sobre qué quieres contactarnos?',
        'contact.placeholder.message': 'Escribe tu mensaje aquí...',
        'contact.terms': 'Acepto la <a href="#" style="color:#00d4ff;">política de privacidad</a>',
        'contact.submit': 'Enviar Mensaje',
        'contact.success.title': 'Mensaje enviado correctamente.',
        'contact.success.subtitle': 'Te responderemos en menos de 48 horas.',

        // ── Auth page ─────────────────────────────────────────────────
        'auth.header.subtitle': 'Accede o crea tu cuenta',
        'auth.toggle.login': 'Iniciar Sesión',
        'auth.toggle.register': 'Registrarse',
        'auth.login.email': 'Email',
        'auth.login.password': 'Contraseña',
        'auth.login.remember': 'Recuérdame',
        'auth.login.forgot': '¿Olvidaste tu contraseña?',
        'auth.login.submit': 'Iniciar Sesión',
        'auth.quick.title': 'Acceso Rápido por Rol',
        'auth.quick.admin': 'Administrador',
        'auth.quick.writer': 'Redactor',
        'auth.quick.collaborator': 'Colaborador',
        'auth.quick.subscriber': 'Suscriptor',
        'auth.register.name': 'Nombre Completo',
        'auth.register.email': 'Email',
        'auth.register.password': 'Contraseña',
        'auth.register.confirm': 'Confirmar Contraseña',
        'auth.register.role': 'Tipo de Cuenta',
        'auth.register.role.subscriber': 'Suscriptor (por defecto)',
        'auth.register.role.collaborator': 'Colaborador',
        'auth.register.role.writer': 'Redactor (requiere invitación)',
        'auth.register.terms': 'Acepto los <a href="#" style="color:#00d4ff;">términos y condiciones</a>',
        'auth.register.submit': 'Crear Cuenta',
        'auth.footer.problems': '¿Problemas? <a href="contact.html">Contacta soporte</a>',
        'auth.placeholder.name': 'Tu nombre completo',
        'auth.placeholder.password_min': 'Mínimo 8 caracteres',
        'auth.placeholder.confirm': 'Repite tu contraseña',

        // ── Dashboard ─────────────────────────────────────────────────
        'dash.menu.main': 'Menú Principal',
        'dash.menu.panel': '📊 Panel General',
        'dash.menu.profile': '👤 Mi Perfil',
        'dash.menu.favorites': '⭐ Favoritos',
        'dash.menu.comments': '💬 Mis Comentarios',
        'dash.menu.content': 'Contenido',
        'dash.menu.news_create': '✍️ Crear Noticia',
        'dash.menu.news_manage': '📝 Gestionar Noticias',
        'dash.menu.admin': 'Administración',
        'dash.menu.users': '👥 Gestionar Usuarios',
        'dash.menu.reports': '📈 Reportes',
        'dash.menu.settings': '⚙️ Configuración',
        'dash.panel.title': 'Panel de Control',
        'dash.stat.news': 'Noticias',
        'dash.stat.favorites': 'Favoritos',
        'dash.stat.comments': 'Comentarios',
        'dash.stat.role': 'Rol',
        'dash.activity.title': 'Actividad Reciente',
        'dash.activity.now': 'Ahora',
        'dash.activity.recent': 'Reciente',
        'dash.activity.login': 'Sesión iniciada como',
        'dash.activity.fav': 'Marcaste como favorito',
        'dash.activity.commented': 'Comentaste:',
        'dash.activity.published': 'Publicaste',
        'dash.activity.drafted': 'Borraste',
        'dash.welcome.subscriber': 'Bienvenido a tu área personal.',
        'dash.welcome.collaborator': 'Bienvenido, colaborador. Crea borradores y aporta a la comunidad.',
        'dash.welcome.writer': 'Bienvenido, redactor. Gestiona las noticias desde aquí.',
        'dash.welcome.admin': 'Panel de administración. Control total de Vortex Play.',
        'dash.profile.title': 'Mi Perfil',
        'dash.profile.name': 'Nombre Completo',
        'dash.profile.email': 'Email (no modificable)',
        'dash.profile.role': 'Rol actual',
        'dash.profile.bio': 'Biografía (opcional)',
        'dash.profile.placeholder_bio': 'Cuéntanos sobre ti...',
        'dash.profile.save': 'Guardar Cambios',
        'dash.favorites.title': 'Juegos Favoritos',
        'dash.favorites.empty': 'No tienes juegos en favoritos.',
        'dash.favorites.explore': 'Explorar Catálogo',
        'dash.favorites.remove': 'Quitar de Favoritos',
        'dash.favorites.press': 'Prensa:',
        'dash.comments.title': 'Mis Comentarios',
        'dash.comments.subtitle': 'Gestiona los comentarios que has publicado',
        'dash.comments.empty': 'No has publicado ningún comentario todavía.',
        'dash.comments.blog_source': 'Artículo de Blog',
        'dash.comments.reactions': 'reacciones',
        'dash.comments.delete': 'Eliminar',
        'dash.news_create.title': 'Crear Nueva Noticia',
        'dash.news_create.subtitle_writer': 'Publica un artículo inmediatamente o guárdalo como borrador.',
        'dash.news_create.subtitle_collab': 'Envía un borrador para que un Redactor o Administrador lo revise y publique.',
        'dash.news_create.label_title': 'Título del Artículo',
        'dash.news_create.placeholder_title': 'Ej: Avance exclusivo del próximo RPG del año',
        'dash.news_create.label_category': 'Categoría',
        'dash.news_create.label_image': 'Fondo Visual',
        'dash.news_create.label_excerpt': 'Resumen Corto',
        'dash.news_create.placeholder_excerpt': '1 o 2 frases de introducción...',
        'dash.news_create.label_content': 'Contenido',
        'dash.news_create.placeholder_content': 'Escribe el cuerpo del artículo...',
        'dash.news_create.publish': 'Publicar Artículo',
        'dash.news_create.publish_collab': 'Enviar a Revisión',
        'dash.news_create.draft': 'Guardar Borrador',
        'dash.news_manage.title': 'Gestionar Noticias',
        'dash.news_manage.subtitle': 'Aprueba borradores o administra las noticias publicadas',
        'dash.news_manage.col_title': 'Título',
        'dash.news_manage.col_author': 'Autor',
        'dash.news_manage.col_status': 'Estado',
        'dash.news_manage.col_date': 'Fecha',
        'dash.news_manage.col_actions': 'Acciones',
        'dash.news_manage.empty': 'No hay noticias registradas.',
        'dash.users.title': 'Gestionar Usuarios',
        'dash.users.subtitle': 'Administra los roles de la plataforma',
        'dash.users.col_name': 'Nombre',
        'dash.users.col_email': 'Email',
        'dash.users.col_role': 'Rol',
        'dash.users.col_actions': 'Acciones',
        'dash.users.suspend': 'Suspender',
        'dash.reports.title': 'Reportes y Estadísticas',
        'dash.reports.subtitle': 'Métricas generales de Vortex Play',
        'dash.reports.news_visits': 'Visitas Noticias',
        'dash.reports.users': 'Usuarios',
        'dash.reports.articles': 'Artículos',
        'dash.reports.role_dist': 'Distribución de Roles',
        'dash.reports.admins': 'Admins',
        'dash.reports.writers': 'Redactores',
        'dash.reports.collaborators': 'Colaboradores',
        'dash.reports.subscribers': 'Suscriptores',
        'dash.settings.title': 'Configuración',
        'dash.settings.subtitle': 'Ajustes globales de la plataforma',
        'dash.settings.allow_reg': 'Permitir nuevos registros',
        'dash.settings.allow_comments': 'Habilitar comentarios',
        'dash.settings.maintenance_label': 'Mensaje de mantenimiento',
        'dash.settings.save': 'Guardar Configuración',

        // ── News article status ───────────────────────────────────────
        'news.status.published': 'Publicada',
        'news.status.draft': 'Borrador',
        'news.status.pending': 'Pendiente',
        'news.action.publish': 'Publicar',
        'news.action.delete': 'Eliminar',
    },
    en: {
        // ── Navigation ──────────────────────────────────────────────
        'nav.home': 'Home',
        'nav.news': 'News',
        'nav.catalog': 'Catalog',
        'nav.blog': 'Blog',
        'nav.agenda': 'Schedule',
        'nav.contact': 'Contact',
        'nav.login': 'Sign In',
        'nav.dashboard': 'Dashboard',
        'nav.logout': 'Log Out',

        // ── Page headers ─────────────────────────────────────────────
        'news.header.title': '📰 News Center',
        'news.header.subtitle': 'Stay up to date with the latest gaming news',
        'games.header.title': '🎮 Game Catalog',
        'games.header.subtitle': 'Best games with press and community ratings',
        'games.sort.label': 'Sort by',
        'games.sort.press': 'Best Press Rating',
        'games.sort.community': 'Best Community Rating',
        'games.sort.year': 'Most Recent',
        'games.sort.az': 'Name (A-Z)',
        'games.filter.genre': 'Genre',
        'games.filter.platform': 'Platform',
        'games.genre.action': 'Action',
        'games.genre.rpg': 'RPG',
        'games.genre.strategy': 'Strategy',
        'games.genre.adventure': 'Adventure',
        'games.platform.pc': 'PC',
        'games.platform.console': 'Consoles',
        'games.platform.mobile': 'Mobile',
        'blog.header.title': '💭 Opinion Blog',
        'blog.header.subtitle': 'In-depth analysis and expert opinions on the gaming industry',
        'agenda.header.title': '📅 Events Schedule',
        'agenda.header.subtitle': 'Game launches, tournaments and gaming events',
        'contact.header.title': '📬 Contact',
        'contact.header.subtitle': 'Get in touch with the Vortex Play team',
        'footer.rights': '© 2026 Vortex Play. All rights reserved.',

        // ── Index ────────────────────────────────────────────────────
        'index.subtitle': 'Gaming platform: news, rankings and community',
        'index.read_more': 'Read more →',

        // ── News sidebar ─────────────────────────────────────────────
        'news.sidebar.categories': 'Categories',
        'news.sidebar.trending': 'Trending',
        'news.sidebar.redaction': 'Editorial',
        'news.cat.all': '📊 All',
        'news.cat.tech': '🚀 Technology',
        'news.cat.esports': '🏆 Esports',
        'news.cat.launches': '🎮 Launches',
        'news.cat.trends': '📈 Trends',
        'news.cat.platforms': '☁️ Platforms',
        'news.cat.streaming': '🎥 Streaming',
        'news.views': 'views',

        // ── Blog sidebar ─────────────────────────────────────────────
        'blog.sidebar.about_title': 'About the Blog',
        'blog.sidebar.about_text': 'Space for in-depth analysis, unfiltered opinions and debate about video games, technology and gaming culture.',
        'blog.sidebar.authors': 'Authors',
        'blog.author1.role': 'eSports Analyst',
        'blog.author2.role': 'Technology and Graphics',

        // ── Comments ─────────────────────────────────────────────────
        'comment.section': 'Comments',
        'comment.empty': 'No comments yet. Be the first!',
        'comment.placeholder': 'Write a comment...',
        'comment.as': 'Commenting as',
        'comment.submit': 'Publish',
        'comment.reply': 'Reply',
        'comment.disabled': 'Comments are temporarily disabled.',
        'comment.login_hint': 'To comment, <a href="auth.html">sign in</a>.',
        'comment.login_react': 'Sign in to react.',
        'comment.login_reply': 'Sign in to reply.',
        'comment.min_chars': 'The comment must be at least 5 characters.',

        // ── Agenda ───────────────────────────────────────────────────
        'agenda.filter.all': 'All',
        'agenda.filter.launch': '🚀 Launches',
        'agenda.filter.tournament': '🏆 Tournaments',
        'agenda.filter.update': '🔄 Updates',
        'agenda.filter.event': '🎪 Events',
        'agenda.weekday.mon': 'Mon',
        'agenda.weekday.tue': 'Tue',
        'agenda.weekday.wed': 'Wed',
        'agenda.weekday.thu': 'Thu',
        'agenda.weekday.fri': 'Fri',
        'agenda.weekday.sat': 'Sat',
        'agenda.weekday.sun': 'Sun',
        'agenda.legend.launch': 'Launch',
        'agenda.legend.tournament': 'Tournament',
        'agenda.legend.update': 'Update',
        'agenda.legend.event': 'Event',
        'agenda.empty': 'Select a day to see events',
        'agenda.type.launch': 'Launch',
        'agenda.type.tournament': 'Tournament',
        'agenda.type.update': 'Update',
        'agenda.type.event': 'Event',
        'agenda.month.0': 'January',
        'agenda.month.1': 'February',
        'agenda.month.2': 'March',
        'agenda.month.3': 'April',
        'agenda.month.4': 'May',
        'agenda.month.5': 'June',
        'agenda.month.6': 'July',
        'agenda.month.7': 'August',
        'agenda.month.8': 'September',
        'agenda.month.9': 'October',
        'agenda.month.10': 'November',
        'agenda.month.11': 'December',

        // ── Roles ────────────────────────────────────────────────────
        'role.admin': 'Admin',
        'role.writer': 'Writer',
        'role.collaborator': 'Collaborator',
        'role.subscriber': 'Subscriber',
        'role.guest': 'Guest',

        // ── Contact form ─────────────────────────────────────────────
        'contact.label.name': 'Full name',
        'contact.label.email': 'Email',
        'contact.label.subject': 'Subject',
        'contact.label.message': 'Message',
        'contact.placeholder.name': 'Your name',
        'contact.placeholder.email': 'you@email.com',
        'contact.placeholder.subject': 'What do you want to contact us about?',
        'contact.placeholder.message': 'Write your message here...',
        'contact.terms': 'I accept the <a href="#" style="color:#00d4ff;">privacy policy</a>',
        'contact.submit': 'Send Message',
        'contact.success.title': 'Message sent successfully.',
        'contact.success.subtitle': 'We will get back to you within 48 hours.',

        // ── Auth page ─────────────────────────────────────────────────
        'auth.header.subtitle': 'Sign in or create your account',
        'auth.toggle.login': 'Sign In',
        'auth.toggle.register': 'Register',
        'auth.login.email': 'Email',
        'auth.login.password': 'Password',
        'auth.login.remember': 'Remember me',
        'auth.login.forgot': 'Forgot your password?',
        'auth.login.submit': 'Sign In',
        'auth.quick.title': 'Quick Access by Role',
        'auth.quick.admin': 'Administrator',
        'auth.quick.writer': 'Writer',
        'auth.quick.collaborator': 'Collaborator',
        'auth.quick.subscriber': 'Subscriber',
        'auth.register.name': 'Full Name',
        'auth.register.email': 'Email',
        'auth.register.password': 'Password',
        'auth.register.confirm': 'Confirm Password',
        'auth.register.role': 'Account Type',
        'auth.register.role.subscriber': 'Subscriber (default)',
        'auth.register.role.collaborator': 'Collaborator',
        'auth.register.role.writer': 'Writer (requires invitation)',
        'auth.register.terms': 'I accept the <a href="#" style="color:#00d4ff;">terms and conditions</a>',
        'auth.register.submit': 'Create Account',
        'auth.footer.problems': 'Problems? <a href="contact.html">Contact support</a>',
        'auth.placeholder.name': 'Your full name',
        'auth.placeholder.password_min': 'Minimum 8 characters',
        'auth.placeholder.confirm': 'Repeat your password',

        // ── Dashboard ─────────────────────────────────────────────────
        'dash.menu.main': 'Main Menu',
        'dash.menu.panel': '📊 Overview',
        'dash.menu.profile': '👤 My Profile',
        'dash.menu.favorites': '⭐ Favorites',
        'dash.menu.comments': '💬 My Comments',
        'dash.menu.content': 'Content',
        'dash.menu.news_create': '✍️ Create Article',
        'dash.menu.news_manage': '📝 Manage Articles',
        'dash.menu.admin': 'Administration',
        'dash.menu.users': '👥 Manage Users',
        'dash.menu.reports': '📈 Reports',
        'dash.menu.settings': '⚙️ Settings',
        'dash.panel.title': 'Control Panel',
        'dash.stat.news': 'Articles',
        'dash.stat.favorites': 'Favorites',
        'dash.stat.comments': 'Comments',
        'dash.stat.role': 'Role',
        'dash.activity.title': 'Recent Activity',
        'dash.activity.now': 'Now',
        'dash.activity.recent': 'Recent',
        'dash.activity.login': 'Logged in as',
        'dash.activity.fav': 'Added to favorites',
        'dash.activity.commented': 'Commented:',
        'dash.activity.published': 'Published',
        'dash.activity.drafted': 'Drafted',
        'dash.welcome.subscriber': 'Welcome to your personal area.',
        'dash.welcome.collaborator': 'Welcome, collaborator. Create drafts and contribute to the community.',
        'dash.welcome.writer': 'Welcome, writer. Manage articles from here.',
        'dash.welcome.admin': 'Administration panel. Full control of Vortex Play.',
        'dash.profile.title': 'My Profile',
        'dash.profile.name': 'Full Name',
        'dash.profile.email': 'Email (not editable)',
        'dash.profile.role': 'Current role',
        'dash.profile.bio': 'Biography (optional)',
        'dash.profile.placeholder_bio': 'Tell us about yourself...',
        'dash.profile.save': 'Save Changes',
        'dash.favorites.title': 'Favorite Games',
        'dash.favorites.empty': 'You have no favorite games.',
        'dash.favorites.explore': 'Explore Catalog',
        'dash.favorites.remove': 'Remove from Favorites',
        'dash.favorites.press': 'Press:',
        'dash.comments.title': 'My Comments',
        'dash.comments.subtitle': 'Manage your published comments',
        'dash.comments.empty': 'You have not published any comments yet.',
        'dash.comments.blog_source': 'Blog Article',
        'dash.comments.reactions': 'reactions',
        'dash.comments.delete': 'Delete',
        'dash.news_create.title': 'Create New Article',
        'dash.news_create.subtitle_writer': 'Publish an article immediately or save it as a draft.',
        'dash.news_create.subtitle_collab': 'Submit a draft for a Writer or Admin to review and publish.',
        'dash.news_create.label_title': 'Article Title',
        'dash.news_create.placeholder_title': 'E.g.: Exclusive preview of the next RPG of the year',
        'dash.news_create.label_category': 'Category',
        'dash.news_create.label_image': 'Visual Background',
        'dash.news_create.label_excerpt': 'Short Summary',
        'dash.news_create.placeholder_excerpt': '1 or 2 introductory sentences...',
        'dash.news_create.label_content': 'Content',
        'dash.news_create.placeholder_content': 'Write the body of the article...',
        'dash.news_create.publish': 'Publish Article',
        'dash.news_create.publish_collab': 'Submit for Review',
        'dash.news_create.draft': 'Save Draft',
        'dash.news_manage.title': 'Manage Articles',
        'dash.news_manage.subtitle': 'Approve drafts or manage published articles',
        'dash.news_manage.col_title': 'Title',
        'dash.news_manage.col_author': 'Author',
        'dash.news_manage.col_status': 'Status',
        'dash.news_manage.col_date': 'Date',
        'dash.news_manage.col_actions': 'Actions',
        'dash.news_manage.empty': 'No articles found.',
        'dash.users.title': 'Manage Users',
        'dash.users.subtitle': 'Manage platform roles',
        'dash.users.col_name': 'Name',
        'dash.users.col_email': 'Email',
        'dash.users.col_role': 'Role',
        'dash.users.col_actions': 'Actions',
        'dash.users.suspend': 'Suspend',
        'dash.reports.title': 'Reports & Statistics',
        'dash.reports.subtitle': 'General Vortex Play metrics',
        'dash.reports.news_visits': 'News Visits',
        'dash.reports.users': 'Users',
        'dash.reports.articles': 'Articles',
        'dash.reports.role_dist': 'Role Distribution',
        'dash.reports.admins': 'Admins',
        'dash.reports.writers': 'Writers',
        'dash.reports.collaborators': 'Collaborators',
        'dash.reports.subscribers': 'Subscribers',
        'dash.settings.title': 'Settings',
        'dash.settings.subtitle': 'Global platform settings',
        'dash.settings.allow_reg': 'Allow new registrations',
        'dash.settings.allow_comments': 'Enable comments',
        'dash.settings.maintenance_label': 'Maintenance message',
        'dash.settings.save': 'Save Settings',

        // ── News article status ───────────────────────────────────────
        'news.status.published': 'Published',
        'news.status.draft': 'Draft',
        'news.status.pending': 'Pending',
        'news.action.publish': 'Publish',
        'news.action.delete': 'Delete',
    }
};

let currentLang = localStorage.getItem('language') || 'es';

function t(key) {
    return (translations[currentLang] && translations[currentLang][key]) || null;
}

function applyTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const val = t(el.getAttribute('data-i18n'));
        if (val !== null) el.textContent = val;
    });

    document.querySelectorAll('[data-i18n-html]').forEach(el => {
        const val = t(el.getAttribute('data-i18n-html'));
        if (val !== null) el.innerHTML = val;
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const val = t(el.getAttribute('data-i18n-placeholder'));
        if (val !== null) el.placeholder = val;
    });

    const btn = document.getElementById('langToggleBtn');
    if (btn) btn.textContent = currentLang === 'es' ? 'EN' : 'ES';

    document.documentElement.lang = currentLang;

    document.dispatchEvent(new CustomEvent('translationsApplied', { detail: { lang: currentLang } }));
}

function toggleLanguage() {
    currentLang = currentLang === 'es' ? 'en' : 'es';
    localStorage.setItem('language', currentLang);
    applyTranslations();
}

document.addEventListener('DOMContentLoaded', function() {
    applyTranslations();
    document.addEventListener('click', function(e) {
        if (e.target && e.target.id === 'langToggleBtn') toggleLanguage();
    });
});
